### ISSUE TITLE
Create statement uses single quote instead of backtick

### ISSUE THREAD

**Issue by allisonletts** [acrosman/csv2sql#2]
**Describe the bug**
I'm getting ``` ' ``` instead of ``` ` ``` in the create statement
**To Reproduce**
1. run node csv2sql.js with any valid csv file and any valid table name
2. copy generated create statement and run in HeidiSQL

**Expected behavior**
I expected the create statement to run without errors
Instead, I received a SQL error (screenshot below).

**Screenshots**
![image](https://user-images.githubusercontent.com/17914696/129423900-edbe53dc-83b6-4c47-8d77-058fffe677a1.png)
![image](https://user-images.githubusercontent.com/17914696/129423974-7b69c44d-3430-4345-b2e4-c7f396a49299.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.1.0
 - Node Version 14.17.5

**Additional context**
Creating table in MariaDB using HeidiSQL

## Workaround
Find/Replace ``` ' ``` with blank worked for this create statement. I believe that using ``` ` ``` would match what you're expecting.

**Comment by acrosman** [comment]
Can you tell I drafted it late at night?
